#home:
#  path: /
#  controller: App\Controller\HomeController::index
#
#property.index:
#  path: /property
#  controller: App\Controller\PropertyController::index
admin:
  path: /admin
  controller: App\Controller\Admin\AdminPropertyController::index